version: '3.8'
services:
  app:
    image: mhdamine48/express-app:staging
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=staging
    restart: unless-stopped
